
module.exports = {
  "ADD_TODO": "ADD_TODO",
  "TOGGLE_TODO": "TOGGLE_TODO",
  "TOGGLE_COMPLETED": "TOGGLE_COMPLETED",
  "CLEAR_COMPLETED": "CLEAR_COMPLETED",
  "LOGIN": "LOGIN",
  "LOGOUT": "LOGOUT",
  "LOGIN_SUCCESSFULL": "LOGIN_SUCCESSFULL",
  "LOGOUT_SUCCESSFULL": "LOGOUT_SUCCESSFULL",
  "SAVE_PROFILE": "SAVE_PROFILE"
};